name: ACtions Workflows

on:
  repository_dispatch:
    types:
      - build
  schedule:
    - cron: '0 * * * *'
  # push:
  #pull_request:
  # types: [closed, assigned, opened, reopened]

env: 
  MY_SECRET: ${{ secrets.MY_SECRET }}

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write 
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail
          
  run-github-actions:
    runs-on: ubuntu-latest
    steps:

      - name: print secret
        run: |
          echo $MY_SECRET

      - name: show payload
        run: |
          echo "${{ github.event.client_payload.env }}"
      - name: List File
        run: |
          pwd
          ls
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: checkout
        uses:  actions/checkout@v1
      - name: List File
        run: |
          pwd
          ls -la
      - name: Simple JS ACtions
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: "Thuc Doan DUy"
      - name: Log Greet Time
        run: echo "${{ steps.greet.outputs.time }}"

      
